[View in Colaboratory](https://colab.research.google.com/github/alvarogutyerrez/alvarogutyerrez/blob/master/numpy_intro.ipynb)

# Business Intelligence para las Finanzas
**Magister en Finanzas**

**Profesor: David Díaz **

**Ayudante: Álvaro Gutiérrez**

---

#Sesión #1:  Intro a Numpy

En esta sesión aprenderemos como ejecutar operaciones básicas del Álgebra Lineal, haciendo uso de librerías de Python. Aprenderemos la diferencia entre los objetos de _pandas_ y _numpy_. De este modo, haciendo uso de operaciones matriciales podremos empezar a trabajar nuestras bases de datos.

Lo primero que debemos notar es que, a diferencia de otros sofwares como $Stata$ o $Matlab$, Python funciona con librerías, las que deben ser cargadas al inicio de nuestro script. En esta sesión haremos uso de las dos librerías mencionadas anteriormente.

Algo importante antes de comenzar, es que debemos resolver ciertos problemas de compatibilidad entre las versiones 2.7 y 3.2 de Python. En particular, el primer argumeto _division_ nos permitirá que cuando computemos $\frac{1}{2}$ el resultado sea $0,5$ y no $0$, error muy común (pero dificil de pesquisar) al iniciar con el software.  El segundo _print_function_ nos permite poder imprimir en la consola ciertos resultados. Finalmente el último nos permitirá operar con caracteres acentuados (e.g, ñ,ó,í,ü...).

Luego cargaremos   _numpy_ con las con la abreviacion _np_. (Que es lo que se ve usualmente en los foros )


In [0]:
from __future__ import division, print_function, unicode_literals
import numpy as np

## Array
Lo primero que aprenderemos será a usar un array (arreglo). 

In [29]:
array_simple = np.array([1,2,3,4])
array_simple

array([1, 2, 3, 4])

Esto también podría haber sido creado con plain python, de la forma

In [30]:
array_plain_python = [1,2,3,4]
array_plain_python

[1, 2, 3, 4]

Los que aparentemente se ven iguales, pero su diferencia es dramáticamente importante a la hora de proceder mediante numeros numéricos debido a que numpy ya tiene definidos toda la operatoria matricial que podríamos llegar a necesitar. Las cuales veremos acontinuación, pero antes de proceder debemos aprender lo que es un arange.

Otra forma con la cual podemos crear una serie de números con array es mediante la estructura **np.array([start],stop,[step])**. Con este generaremos una secuencia de numeros del 1 al 9 (recordar que python comienza a contar desde el cero) avanzando gradualmente de uno en uno.

In [31]:
array_1_10 = np.arange(1,10,1)
array_1_10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##Arange 
Este objeto nos permite darle forma a la secuencia de números que acabamos de crear. Por ejemplo, podemos crear una matriz de 3x3 con los 9 dígitos creados anteriormente.

In [32]:
arange_33  = array_1_10.reshape(3,3)
arange_33


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Del mismo modo, podríamos crear una matriz de 3x4 en una sola linea de la siguiente forma.

In [33]:
arange_34  = np.arange(1, 13, 1).reshape(3,4)
arange_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Extraccion de Datos por Coordenadas

Podemos extraer información desde nuestros aray ocupando el operador **aray[ x ,  y ]**. En el cual $X$ es la fila y $Y$ la columna. Abajo se listan una serie de ejemplos 

In [34]:
#Elemento en la coordenada 0,0 (Primer elemento)
elemento_0_0 = arange_34[0 , 0 ]
elemento_0_0

1

In [35]:
#Elemento útima fila y última columna 
#El menos uno denota el último elemento, el menos dos el penúltimo y así sucesivamente...
last_element = arange_34[-1 , -1 ]
last_element

12

In [36]:
#Primera columna de la matriz 3x4
col1 = arange_34[: , 0 ]
print(col1)


[1 5 9]


In [37]:
#Primera fila de la matriz 3x4
fila1 = arange_34[0,:]
(print(fila1))

[1 2 3 4]


## Operaciones Matriciales Elementales

Numpy cuenta con una gama de operaciones numéricas incontables, en este apartado listaremos las más comunes.




In [38]:
#Producto punto
dot_product = arange_33[0,:].dot(arange_34[:,0])
print(arange_33[0,:])
print(arange_34[:,0])
print(dot_product)

[1 2 3]
[1 5 9]
38


In [39]:
#Multiplicacion
mult = arange_33.dot(arange_34)
print('Primera matriz')
print(arange_33)
print('Segunda matriz')
print(arange_34)
print('Producto')

mult

Primera matriz
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Segunda matriz
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Producto


array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

In [40]:
#Traspuesto
trasp = np.transpose(arange_34)
trasp

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Looping (for)

En este apartado mostratemos una forma sencilla de recorrer todos los elementos de una matriz mediante un loop doble ( for dentro de for). Para realizar esto necesitamos una serie de cosas:

1.  Un loop para las filas, indexado con el subindice $i$.
2. Un loop para las columnas indexado con el subindice $j$.
3. La cantidad de filas y columnas de la matriz, las cuales determinarán la amplitud del loop.

En términos teóricos tendremos que queremos recorrer el arreglo

\begin{bmatrix}
    x_{12}       & x_{12} & x_{13} & x_{14} \\
    x_{21}       & x_{22} & x_{23} &  x_{24} \\
    x_{d1}       & x_{d2} & x_{d3} &  x_{34}
\end{bmatrix} 

El que en nuestro caso tiene la forma 

\begin{bmatrix}
   1       & 2& 3 & 4 \\
    5 & 6 & 7 &  8 \\
9    & 10 & 11 & 12
\end{bmatrix} 

De este modo $i$ estará definido desde el $1$ al $3$, dado que tenemos 3 filas y $j$ lo estará desde el $1$ al $4$ ya que tenemos 4 columnas.

De este modo solamente nos queda recuperar el punto tres de la lista anterior. El cual nos dice que debemos recuperar la cantidad de filas y columnas. Esto se hará como sigue.






In [41]:
filas_total= arange_34.shape[0] #filas 
print(filas_total)
columas_total = arange_34.shape[1] #columnas
print(columas_total)

3
4


## Loop de prueba (Recorrer toda la matriz)

Con los ingredientes predefinidos en el cuadro anterior ya podemos construir un loop sencillo que nos muestre todos los elementos contenidos en nuestra matriz. Este se construirá ocupando el comando **range** el cual nos permite desplegar una serie de números con la sitaxis range(inicio,final). En donde, en este caso, como queremos recorrer _toda_ la matriz, partimos desde el cero hasta el número total de filas y columnas, respectivamente.

Luego de esto, ejecutamos el comando print del elemento [$i$,$j$] que no es nada más que el elemento contenido en la posición $i$,$j$ tal como vimos anteriormente.*texto en cursiva*

In [43]:
'''for de inspeccion '''
for i in range(0,filas_total ):
    for j in range(0,columas_total ):
        print(arange1_34[i , j])

1
2
3
4
5
6
7
8
9
10
11
12


## Loop de práctica.
#### Réplica de la multiplicacion de matrices

Ahora recordando un poco de nuestras clases de álgebra lineal, sabemos que la multiplicacion de matrices no es más que una serie de productos punto a lo largo de las coordenadas de la matriz.

$$ 
\begin{bmatrix}
    x_{1,1}  &      x_{1,2} &     x_{1,3}      \\
   x_{2,1}  &      x_{2,2} &     x_{2,3}  \\
      x_{3,1}  &      x_{3,2} &     x_{3,3} 
\end{bmatrix}
* 
\begin{bmatrix}
   y_{1,1}  &      y_{1,2} &     y_{1,3} &  y_{1,4}   \\
   y_{2,1}  &      y_{2,2} &     y_{2,3} & y_{2,4}   \\
   y_{3,1}  &      y_{3,2} &     y_{3,3} & y_{3,4}   
\end{bmatrix} 
=
\begin{bmatrix}  
  (x_{1,1}*    y_{1,1}  + x_{1,2}* y_{2,1}  + x_{1,3}* y_{3,1})    &       (x_{1,1}*    y_{1,2}  + x_{1,2}* y_{2,2}  + x_{1,3}* y_{3,2}  )& ( x_{1,1}*    y_{1,3}  + x_{1,2}* y_{2,3}  + x_{1,3}* y_{3,3}) &  (x_{1,1}*    y_{1,4}  + x_{1,2}* y_{2,4}  + x_{1,3}* y_{3,4}  )  \\ 
  (x_{2,1}*    y_{1,1}  + x_{2,2}* y_{2,1}  + x_{2,3}* y_{3,1})    &       (x_{2,1}*    y_{1,2}  + x_{2,2}* y_{2,2}  + x_{2,3}* y_{3,2}  )& ( x_{2,1}*    y_{1,3}  + x_{2,2}* y_{2,3}  + x_{2,3}* y_{3,3}) &  (x_{2,1}*    y_{1,4}  + x_{2,2}* y_{2,4}  + x_{2,3}* y_{3,4}  )  \\
    (x_{3,1}*    y_{1,1}  + x_{3,2}* y_{2,1}  + x_{3,3}* y_{3,1})    &       (x_{3,1}*    y_{1,2}  + x_{3,2}* y_{2,2}  + x_{3,3}* y_{3,2}  )& ( x_{3,1}*    y_{1,3}  + x_{3,2}* y_{2,3}  + x_{3,3}* y_{3,3}) &  (x_{3,1}*    y_{1,4}  + x_{3,2}* y_{2,4}  + x_{3,3}* y_{3,4}  )  \\
\end{bmatrix} 
$$

\\

Lo que si miramos con cuidado, no es más que un producto punto que recorre en filas y columnas toda la matriz. Esto es justamente lo que programaremos en un for dentro de un for. Ocuparemos la estructura definida previamente para realizar el producto punto en filas y columnas.



In [49]:
#Generamos una matriz de ceros donde almacenaremos los resultados
producto_loop= np.zeros([3,4])
#Inicio del for para filas
for i in range(0,filas_total ):
    #Inicio del for para columnas
    for j in range(0,columas_total ):
        #Extraccion de las filas
        rows=arange_33[i,:]
        #Extraccion de las columnas
        cols=arange_34[:,j] 
        #Producto punto entre ambas.
        producto_loop[i,j] = rows.dot(cols)
                    
      
     
print(producto_loop)
print()
print('Para comprobar, revisemos la multiplicacion hecha mediante la librería numpy')
print(mult) 

[[ 38.  44.  50.  56.]
 [ 83.  98. 113. 128.]
 [128. 152. 176. 200.]]

Para comprobar, revisemos la multiplicacion hecha mediante la librería numpy
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


##                            _**voilà!**_
     