[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alvarogutyerrez/alvarogutyerrez/blob/master/S08_Modelos_Multinomiales.ipynb)

In [0]:
!wget https://www.dropbox.com/s/82dl9cn3p59bxuv/data_with_economic_stage.txt
!pip install xlrd

##Preliminares

Generacion de la data

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
data=pd.read_csv('data_with_economic_stage.txt',sep='\t')
y=data['economic_stage']
x=data.iloc[:,2:-2]
y.describe()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50)

## Cargando Modelos

In [0]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

# One versus Rest con Regresión Logistica (LR)

In [0]:
logistic_ovr=LogisticRegression(multi_class='ovr',penalty='l1')
logistic_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_ovr.coef_)
ctes=pd.DataFrame(logistic_ovr.intercept_)

y_pred_train=np.asarray(logistic_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_ovr.predict(X_test),dtype='str')

y_proba_train=logistic_ovr.predict_proba(X_train)
y_proba_test=logistic_ovr.predict_proba(X_test)


In [11]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)


             precision    recall  f1-score   support

  cluster-1       0.94      0.99      0.96       203
  cluster-2       0.77      0.50      0.61        20
  cluster-3       1.00      0.82      0.90        11

avg / total       0.93      0.94      0.93       234



array([[200,   3,   0],
       [ 10,  10,   0],
       [  2,   0,   9]])

In [12]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.95      0.97      0.96       207
  cluster-2       0.86      0.67      0.75        18
  cluster-3       0.44      0.44      0.44         9

avg / total       0.92      0.92      0.92       234



array([[200,   2,   5],
       [  6,  12,   0],
       [  5,   0,   4]])

#One Versus Rest con sklearn.multiclass

In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression


In [0]:
clasif_ovr=OneVsRestClassifier(LogisticRegression(penalty='l1'))
clasif_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(clasif_ovr.coef_)
ctes=pd.DataFrame(clasif_ovr.intercept_)

y_pred_train=np.asarray(clasif_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(clasif_ovr.predict(X_test),dtype='str')

y_proba_train=clasif_ovr.predict_proba(X_train)
y_proba_test=clasif_ovr.predict_proba(X_test)


In [16]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)



             precision    recall  f1-score   support

  cluster-1       0.96      0.99      0.97       203
  cluster-2       0.81      0.65      0.72        20
  cluster-3       1.00      0.91      0.95        11

avg / total       0.95      0.95      0.95       234



array([[200,   3,   0],
       [  7,  13,   0],
       [  1,   0,  10]])

In [17]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.96      0.97      0.97       207
  cluster-2       0.76      0.72      0.74        18
  cluster-3       0.75      0.67      0.71         9

avg / total       0.94      0.94      0.94       234



array([[201,   4,   2],
       [  5,  13,   0],
       [  3,   0,   6]])

# One Versus One con sklearn.multiclass 

In [0]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.linear_model import LogisticRegression

In [20]:
clasif_ovo=OneVsOneClassifier(LogisticRegression(penalty='l1'))
clasif_ovo.fit(X_train,y_train)


OneVsOneClassifier(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
          n_jobs=1)

In [0]:
y_pred_train=np.asarray(clasif_ovo.predict(X_train),dtype='str')
y_pred_test=np.asarray(clasif_ovo.predict(X_test),dtype='str')

In [25]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)


             precision    recall  f1-score   support

  cluster-1       0.99      1.00      1.00       203
  cluster-2       1.00      0.90      0.95        20
  cluster-3       1.00      1.00      1.00        11

avg / total       0.99      0.99      0.99       234



array([[203,   0,   0],
       [  2,  18,   0],
       [  0,   0,  11]])

In [24]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.98      0.98      0.98       207
  cluster-2       0.89      0.89      0.89        18
  cluster-3       0.75      0.67      0.71         9

avg / total       0.96      0.96      0.96       234



array([[203,   2,   2],
       [  2,  16,   0],
       [  3,   0,   6]])

# Regresion Softmax ocupando LR 

In [0]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

In [0]:

logistic_smax=LogisticRegression(multi_class='multinomial',solver='lbfgs', penalty='l2')
logistic_smax.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_smax.coef_)
ctes=pd.DataFrame(logistic_smax.intercept_)

y_pred_train=np.asarray(logistic_smax.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_smax.predict(X_test),dtype='str')

y_proba_train=logistic_smax.predict_proba(X_train)
y_proba_test=logistic_smax.predict_proba(X_test)

In [28]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

             precision    recall  f1-score   support

  cluster-1       0.97      0.98      0.98       203
  cluster-2       0.89      0.85      0.87        20
  cluster-3       0.80      0.73      0.76        11

avg / total       0.96      0.96      0.96       234



array([[199,   2,   2],
       [  3,  17,   0],
       [  3,   0,   8]])

In [29]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)


             precision    recall  f1-score   support

  cluster-1       0.97      0.95      0.96       207
  cluster-2       0.67      0.78      0.72        18
  cluster-3       0.60      0.67      0.63         9

avg / total       0.93      0.92      0.93       234



array([[196,   7,   4],
       [  4,  14,   0],
       [  3,   0,   6]])

#Balanceo de Clases

##Sub-balanceo (Clase más pequeña)

In [62]:
data_clase1 = data[data['economic_stage'] =='cluster-1'].sample(n=17 ,  random_state =777)
data_clase2 = data[data['economic_stage'] =='cluster-2'].sample(n=17 ,  random_state =777)
data_clase3 = data[data['economic_stage'] =='cluster-3'].sample(n=17 ,  random_state =777 )

under_sample=data_clase1.append(data_clase2, ignore_index=True)
under_sample = under_sample.append(data_clase3 ,ignore_index=True)
under_sample

under_sample['economic_stage'].value_counts()


cluster-3    17
cluster-2    17
cluster-1    17
Name: economic_stage, dtype: int64

In [0]:

y=under_sample['economic_stage']
x=under_sample.iloc[:,2:-2]
y.describe()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50)

In [68]:
logistic_ovr=LogisticRegression(multi_class='ovr',penalty='l1')
logistic_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_ovr.coef_)
ctes=pd.DataFrame(logistic_ovr.intercept_)

y_pred_train=np.asarray(logistic_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_ovr.predict(X_test),dtype='str')

y_proba_train=logistic_ovr.predict_proba(X_train)
y_proba_test=logistic_ovr.predict_proba(X_test)


print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

             precision    recall  f1-score   support

  cluster-1       1.00      1.00      1.00         9
  cluster-2       1.00      1.00      1.00         8
  cluster-3       1.00      1.00      1.00         8

avg / total       1.00      1.00      1.00        25



array([[9, 0, 0],
       [0, 8, 0],
       [0, 0, 8]])

##Sobre-balanceo (Clase más grande)

In [72]:
data['economic_stage'].value_counts()

cluster-1    410
cluster-2     38
cluster-3     20
Name: economic_stage, dtype: int64

In [76]:
data_clase1 = data[data['economic_stage'] =='cluster-1'].sample(n=410 , replace =True , random_state =777 )
data_clase2 = data[data['economic_stage'] =='cluster-2'].sample(n=410 , replace =True , random_state =777 )
data_clase3 = data[data['economic_stage'] =='cluster-3'].sample(n=410 , replace =True , random_state =777 )

over_sample=data_clase1.append(data_clase2, ignore_index=True)
over_sample = over_sample.append(data_clase3 ,ignore_index=True)
over_sample

over_sample['economic_stage'].value_counts()

cluster-3    410
cluster-2    410
cluster-1    410
Name: economic_stage, dtype: int64

In [0]:
y=over_sample['economic_stage']
x=over_sample.iloc[:,2:-2]
y.describe()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50)

# Métricas 



In [78]:
logistic_ovr=LogisticRegression(multi_class='ovr',penalty='l1')
logistic_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_ovr.coef_)
ctes=pd.DataFrame(logistic_ovr.intercept_)

y_pred_train=np.asarray(logistic_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_ovr.predict(X_test),dtype='str')

y_proba_train=logistic_ovr.predict_proba(X_train)
y_proba_test=logistic_ovr.predict_proba(X_test)


print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

             precision    recall  f1-score   support

  cluster-1       0.90      0.91      0.91       205
  cluster-2       0.95      0.95      0.95       205
  cluster-3       0.97      0.95      0.96       205

avg / total       0.94      0.94      0.94       615



array([[187,  11,   7],
       [ 11, 194,   0],
       [ 10,   0, 195]])