<a href="https://colab.research.google.com/github/alvarogutyerrez/alvarogutyerrez/blob/master/S08_Modelos_Multinomiales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!wget https://www.dropbox.com/s/82dl9cn3p59bxuv/data_with_economic_stage.txt
!pip install xlrd

--2018-10-17 16:24:09--  https://www.dropbox.com/s/82dl9cn3p59bxuv/data_with_economic_stage.txt
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/82dl9cn3p59bxuv/data_with_economic_stage.txt [following]
--2018-10-17 16:24:09--  https://www.dropbox.com/s/raw/82dl9cn3p59bxuv/data_with_economic_stage.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc24cec70c58800b721fc08ed242.dl.dropboxusercontent.com/cd/0/inline/ATMM9g2oXEBEqYJF4eWLpjV8ntL-SG_t94wA3IXZFX2U_RMDLuN8duCxVD35A6tGcYbQQ58XWuMPrl_GlrkueBHj33MY6jYofPJbv3DOOIYMM_mgDZOvic9re8MBKsAIWKx6AtBcE48Y0se1_ln8mLoHtfqWU1DOGxaJr6JFq5r3dXy2p1uEFFZ7zRUSP6eixnGCIm_w0RoSnlJPNhaRpVr6/file [following]
--2018-10-17 16:24:10--  https://uc24cec70c58800b721fc08ed242.dl.dropboxuserconten

##Preliminares

Generacion de la data

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


data=pd.read_csv('data_with_economic_stage.txt',sep='\t')
y=data['economic_stage']
x=data.iloc[:,2:-2]
y.describe()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50)

## Cargando Modelos

In [0]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

# One versus Rest con Regresión Logistica (LR)

In [0]:
logistic_ovr=LogisticRegression(multi_class='ovr',penalty='l1')
logistic_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_ovr.coef_)
ctes=pd.DataFrame(logistic_ovr.intercept_)

y_pred_train=np.asarray(logistic_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_ovr.predict(X_test),dtype='str')

y_proba_train=logistic_ovr.predict_proba(X_train)
y_proba_test=logistic_ovr.predict_proba(X_test)


In [11]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)


             precision    recall  f1-score   support

  cluster-1       0.97      1.00      0.98       208
  cluster-2       1.00      0.67      0.80        15
  cluster-3       1.00      0.82      0.90        11

avg / total       0.97      0.97      0.97       234



array([[208,   0,   0],
       [  5,  10,   0],
       [  2,   0,   9]])

In [12]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.96      0.98      0.97       202
  cluster-2       0.75      0.65      0.70        23
  cluster-3       1.00      0.89      0.94         9

avg / total       0.94      0.94      0.94       234



array([[197,   5,   0],
       [  8,  15,   0],
       [  1,   0,   8]])

#One Versus Rest con sklearn.multiclass

In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression


In [0]:
clasif_ovr=OneVsRestClassifier(LogisticRegression(penalty='l1'))
clasif_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(clasif_ovr.coef_)
ctes=pd.DataFrame(clasif_ovr.intercept_)

y_pred_train=np.asarray(clasif_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(clasif_ovr.predict(X_test),dtype='str')

y_proba_train=clasif_ovr.predict_proba(X_train)
y_proba_test=clasif_ovr.predict_proba(X_test)


In [15]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)



             precision    recall  f1-score   support

  cluster-1       0.97      1.00      0.99       208
  cluster-2       1.00      0.73      0.85        15
  cluster-3       1.00      0.82      0.90        11

avg / total       0.98      0.97      0.97       234



array([[208,   0,   0],
       [  4,  11,   0],
       [  2,   0,   9]])

In [16]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.98      0.98      0.98       202
  cluster-2       0.83      0.83      0.83        23
  cluster-3       1.00      0.89      0.94         9

avg / total       0.96      0.96      0.96       234



array([[198,   4,   0],
       [  4,  19,   0],
       [  1,   0,   8]])

# One Versus One con sklearn.multiclass 

In [0]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.linear_model import LogisticRegression

In [18]:
clasif_ovo=OneVsOneClassifier(LogisticRegression(penalty='l1'))
clasif_ovo.fit(X_train,y_train)


OneVsOneClassifier(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
          n_jobs=1)

In [0]:
y_pred_train=np.asarray(clasif_ovo.predict(X_train),dtype='str')
y_pred_test=np.asarray(clasif_ovo.predict(X_test),dtype='str')

In [20]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)


             precision    recall  f1-score   support

  cluster-1       0.99      1.00      0.99       208
  cluster-2       1.00      1.00      1.00        15
  cluster-3       1.00      0.73      0.84        11

avg / total       0.99      0.99      0.99       234



array([[208,   0,   0],
       [  0,  15,   0],
       [  3,   0,   8]])

In [21]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.97      0.97      0.97       202
  cluster-2       0.83      0.83      0.83        23
  cluster-3       0.67      0.67      0.67         9

avg / total       0.94      0.94      0.94       234



array([[195,   4,   3],
       [  4,  19,   0],
       [  3,   0,   6]])

# Regresion Softmax ocupando LR 

In [0]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

In [0]:

logistic_smax=LogisticRegression(multi_class='multinomial',solver='lbfgs', penalty='l2')
logistic_smax.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_smax.coef_)
ctes=pd.DataFrame(logistic_smax.intercept_)

y_pred_train=np.asarray(logistic_smax.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_smax.predict(X_test),dtype='str')

y_proba_train=logistic_smax.predict_proba(X_train)
y_proba_test=logistic_smax.predict_proba(X_test)

In [24]:
print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

             precision    recall  f1-score   support

  cluster-1       0.94      0.98      0.96       208
  cluster-2       0.82      0.60      0.69        15
  cluster-3       0.62      0.45      0.53        11

avg / total       0.92      0.93      0.92       234



array([[203,   2,   3],
       [  6,   9,   0],
       [  6,   0,   5]])

In [25]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)


             precision    recall  f1-score   support

  cluster-1       0.96      0.97      0.96       202
  cluster-2       0.79      0.65      0.71        23
  cluster-3       0.80      0.89      0.84         9

avg / total       0.93      0.94      0.93       234



array([[196,   4,   2],
       [  8,  15,   0],
       [  1,   0,   8]])

#Balanceo de Clases

##Sub-balanceo (Clase más pequeña)

In [26]:
data_clase1 = data[data['economic_stage'] =='cluster-1'].sample(n=17 ,  random_state =777)
data_clase2 = data[data['economic_stage'] =='cluster-2'].sample(n=17 ,  random_state =777)
data_clase3 = data[data['economic_stage'] =='cluster-3'].sample(n=17 ,  random_state =777 )

under_sample=data_clase1.append(data_clase2, ignore_index=True)
under_sample = under_sample.append(data_clase3 ,ignore_index=True)
under_sample

under_sample['economic_stage'].value_counts()


cluster-3    17
cluster-2    17
cluster-1    17
Name: economic_stage, dtype: int64

In [0]:

y=under_sample['economic_stage']
x=under_sample.iloc[:,2:-2]
y.describe()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50)

In [28]:
logistic_ovr=LogisticRegression(multi_class='ovr',penalty='l1')
logistic_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_ovr.coef_)
ctes=pd.DataFrame(logistic_ovr.intercept_)

y_pred_train=np.asarray(logistic_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_ovr.predict(X_test),dtype='str')

y_proba_train=logistic_ovr.predict_proba(X_train)
y_proba_test=logistic_ovr.predict_proba(X_test)


print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

             precision    recall  f1-score   support

  cluster-1       1.00      1.00      1.00         8
  cluster-2       1.00      1.00      1.00         9
  cluster-3       1.00      1.00      1.00         8

avg / total       1.00      1.00      1.00        25



array([[8, 0, 0],
       [0, 9, 0],
       [0, 0, 8]])

##Sobre-balanceo (Clase más grande)

In [29]:
data['economic_stage'].value_counts()

cluster-1    410
cluster-2     38
cluster-3     20
Name: economic_stage, dtype: int64

In [30]:
data_clase1 = data[data['economic_stage'] =='cluster-1'].sample(n=410 , replace =True , random_state =777 )
data_clase2 = data[data['economic_stage'] =='cluster-2'].sample(n=410 , replace =True , random_state =777 )
data_clase3 = data[data['economic_stage'] =='cluster-3'].sample(n=410 , replace =True , random_state =777 )

over_sample=data_clase1.append(data_clase2, ignore_index=True)
over_sample = over_sample.append(data_clase3 ,ignore_index=True)
over_sample

over_sample['economic_stage'].value_counts()

cluster-3    410
cluster-2    410
cluster-1    410
Name: economic_stage, dtype: int64

In [0]:
y=over_sample['economic_stage']
x=over_sample.iloc[:,2:-2]
y.describe()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50)

# Métricas 



In [32]:
logistic_ovr=LogisticRegression(multi_class='ovr',penalty='l1')
logistic_ovr.fit(X_train,y_train)

coeficientes=pd.DataFrame(logistic_ovr.coef_)
ctes=pd.DataFrame(logistic_ovr.intercept_)

y_pred_train=np.asarray(logistic_ovr.predict(X_train),dtype='str')
y_pred_test=np.asarray(logistic_ovr.predict(X_test),dtype='str')

y_proba_train=logistic_ovr.predict_proba(X_train)
y_proba_test=logistic_ovr.predict_proba(X_test)


print(classification_report(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

             precision    recall  f1-score   support

  cluster-1       0.94      0.93      0.94       211
  cluster-2       0.95      0.94      0.94       194
  cluster-3       0.98      1.00      0.99       210

avg / total       0.96      0.96      0.96       615



array([[196,  10,   5],
       [ 12, 182,   0],
       [  0,   0, 210]])

In [33]:
print(classification_report(y_test, y_pred_test))
confusion_matrix(y_test, y_pred_test)

             precision    recall  f1-score   support

  cluster-1       0.95      0.92      0.94       199
  cluster-2       0.95      0.95      0.95       216
  cluster-3       0.98      1.00      0.99       200

avg / total       0.96      0.96      0.96       615



array([[184,  10,   5],
       [ 10, 206,   0],
       [  0,   0, 200]])